# Generated by Django 4.2 on 2023-04-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
