# Generated by Django 4.2 on 2023-04-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
