# Generated by Django 4.2 on 2023-04-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speechEmotionRecognition', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
